### ISSUE TITLE
Outsource dependencies.

### ISSUE THREAD

**Issue by ghost** [noahrepublic/DataKeep#7]
I would suggest to outsource signal & promise to wally. This would make managing sub-dependencies a better experience for the developer.

**Comment by noahrepublic** [comment]
Finished, due to Signal being in shared realm it requires the user to define in their wally.toml:

```toml
[place]
shared-packages = "game.ReplicatedStorage.Packages"
```
